spring.application.name=platforma-auto

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/car_app
spring.datasource.username=greg
spring.datasource.password=grishaC185
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# JWT
jwt.secret=Y2FyLWFwcC1qd3Qtc2VjcmV0LWtleS0yMDI2LXNlbW5hdHVyYS1zaWd1cmEtbHVuZ2EtYmF6YTY0
jwt.expiration-ms=86400000
